name: Account Request Implement

on:
  issues:
    types:
      - labeled

jobs:
  # When ACCOUNT_IMPLEMENTED label is added to account management request
  request-implemented:
    if: github.event.label.name == 'ACCOUNT_IMPLEMENTED'
    runs-on: ubuntu-20.04
    permissions:
      issues: write
    steps:
      - name: Notify Blossom Assessors about Implemented Account
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            @usnistgov/blossom-assessors An edit to the ACL and/or SSP has been implemented.
            Please monitor the automated assessment.
      
      - name: Checkout repo to access handshake file
        uses: actions/checkout@v3
      
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
      
      - name: Copy handshake to bucket
        run: |
          aws s3 cp .sims/handshake/handshake_empty s3://"$AWS_BUCKET"
        env:
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}